const test=require('node:test'),assert=require('node:assert/strict');const {boot}=require('./dom-helper.cjs');
test('all local modules boot with real HTML in simulated DOM',async()=>{const h=await boot();try{assert.deepEqual(h.errors,[]);assert.ok(h.w.ERPOrderFlow);assert.ok(h.w.LocalFileStore);assert.equal(typeof h.w.saveInvoice,'function');assert.equal(h.w.document.querySelectorAll('input[name="p-vat"][value="2"]').length,1);}finally{h.close();}});
test('quote → SO → two deliveries → receipt + billing payment → reversal',async()=>{
 const h=await boot(),{w,set}=h;try{
  w.selBr('q','ubon');set('q-no','QT-TEST');set('q-date','2026-09-05');set('q-cust','ลูกค้าทดสอบ');set('q-address','ที่อยู่ใหม่');set('q-tax-id','1234567890123');set('q-vat','1');w.document.getElementById('q-items-body').innerHTML='';w.addQItem({product:'งานบริการทดสอบ',qty:10,price:100,unitPrice:100,priceUnit:100,unit:'ชิ้น'});await w.saveQuote();
  let pack=w.loadFor('ubon',2026,8);assert.equal(pack.quotes.length,1,JSON.stringify(h.messages));let q=pack.quotes[0];assert.equal(q.total,1070);q.approved=true;w.saveFor('ubon',2026,8,pack);
  for(const [id,value] of Object.entries({'erp-so-no':'SO-TEST','erp-so-date':'2026-09-05'})){const el=w.document.createElement('input');el.id=id;el.value=value;w.document.body.append(el);}
  w.testFlow.saveSalesOrderFromQuote({...q,_branch:'ubon',_year:2026,_month:8},{b:'ubon',y:2026,m:8,id:q.id});let o=w.ERPOrderFlow.getStore().salesOrders[0];assert.ok(o,JSON.stringify(h.messages));
  let store=w.ERPOrderFlow.getStore();store.salesOrders[0].items[0].readyQty=10;store.salesOrders[0].items[0].productionQty=10;w.localStorage.setItem(w.ComformTenant.storageKey('example_erp_order_flow_v3'),JSON.stringify(store));
  set('i-address','OLD ADDRESS');set('i-tax-id','OLD TAX');w.ERPOrderFlow.prepareDelivery(o.id);assert.equal(w.document.getElementById('i-address').value,'ที่อยู่ใหม่');assert.equal(w.document.getElementById('i-tax-id').value,'1234567890123');
  set('i-date','2026-09-05');set('i-no','INV-TEST-1');w.document.querySelector('#i-items-body [data-field="qty"]').value=3;w.calcI();await w.saveInvoice();
  let data=w.ERPIntegrity.business();assert.equal(data.invoices.length,1,JSON.stringify(h.messages));assert.equal(data.invoices[0].total,321);assert.equal(w.ERPIntegrity.orderProgress(o).items[0].remainingQty,7);
  w.selBr('r','ubon');set('r-no','R-TEST');set('r-date','2026-09-05');set('r-cust',q.customer);set('r-inv-no','INV-TEST-1');set('r-vat','0');w.document.getElementById('r-items-body').innerHTML='';w.addRItem({product:'ชำระบางส่วน',qty:1,priceUnit:100,unit:'ครั้ง'});await w.saveReceipt();
  data=w.ERPIntegrity.business();assert.equal(data.receipts.length,1,JSON.stringify(h.messages));assert.equal(w.ERPIntegrity.paymentSummary(data.invoices[0]).outstanding,221);
  w.ERPOrderFlow.prepareDelivery(o.id);assert.equal(Number(w.document.querySelector('#i-items-body [data-field="qty"]').value),7);set('i-date','2026-09-05');set('i-no','INV-TEST-2');await w.saveInvoice();data=w.ERPIntegrity.business();assert.equal(data.invoices.length,2,JSON.stringify(h.messages));assert.equal(w.ERPIntegrity.orderProgress(o).items[0].remainingQty,0);
  // Use the actual billing save functions with the same fields as the modal.
  for(const [id,value] of Object.entries({'erp-bill-no':'BILL-TEST','erp-bill-date':'2026-09-05','erp-pay-no':'PAY-TEST','erp-pay-date':'2026-09-05','erp-pay-total':'970','erp-pay-method':'เงินสด'})){const el=w.document.createElement('input');el.id=id;el.value=value;w.document.body.append(el);}
  data.invoices.forEach((inv,idx)=>{const row=w.document.createElement('div');row.dataset.billingLine=idx;const input=w.document.createElement('input');input.className='erp-bill-amount';input.value=w.ERPIntegrity.paymentSummary(inv).outstanding;row.append(input);w.document.body.append(row);});
  w.testFlow.saveBilling(data.invoices);const b=w.ERPOrderFlow.getStore().billingNotes[0];assert.equal(b.totalBilled,970);w.testFlow.saveBillingPayment(b,b.lines);store=w.ERPOrderFlow.getStore();assert.equal(store.payments.length,1,JSON.stringify(h.messages));assert.equal(w.ERPIntegrity.business().receipts.length,3);assert.equal(w.testFlow.derivedOrderStage(o),'completed');
  w.ERPOrderFlow.voidPayment(store.payments[0].id);assert.equal(w.testFlow.derivedOrderStage(o),'delivered');assert.equal(w.ERPIntegrity.business().invoices.reduce((s,i)=>s+w.ERPIntegrity.paymentSummary(i).outstanding,0),970);
  assert.deepEqual(h.errors,[]);
 }finally{h.close();}
});
test('JSON merge preserves prior master/order and backup captured before import',async()=>{const h=await boot(),{w,set}=h;try{w.testApp.restoreLocalMasterBackup({contacts:[{id:'OLD-C',name:'เดิม'}],orderFlow:{salesOrders:[{id:'OLD-SO'}]}});set('import-mode','merge');const raw={masterData:{contacts:[{id:'NEW-C',name:'ใหม่'}],orderFlow:{salesOrders:[{id:'NEW-SO'}]}}};await w.importJSON({target:{files:[{text:async()=>JSON.stringify(raw)}],value:'file'}});assert.ok(w.contactMasterRows().some(c=>c.id==='OLD-C'));assert.ok(w.contactMasterRows().some(c=>c.id==='NEW-C')); assert.equal(w.ERPOrderFlow.getStore().salesOrders.length,2);const keys=Object.keys(w.localStorage).filter(k=>k.includes('auto_backup'));assert.ok(keys.length);const backup=JSON.parse(w.localStorage.getItem(keys[0]));assert.ok(JSON.stringify(backup).includes('OLD-C'));assert.ok(!JSON.stringify(backup).includes('NEW-C'));assert.deepEqual(h.errors,[]);}finally{h.close();}});
test('invoice form stock guard rejects duplicate rows above on-hand quantity',async()=>{const h=await boot(),{w,set}=h;try{const p={id:'TEST-P',code:'TEST-P',name:'สต๊อกทดสอบ',flowType:'inventory',fulfillmentType:'stock',openingStockUbon:10,openingStockKhonkaen:0,unit:'ชิ้น'};w.testApp.restoreLocalMasterBackup({products:[p]});w.selBr('i','ubon');set('i-no','INV-STOCK');set('i-date','2026-09-05');set('i-cust','ทดสอบ');w.document.getElementById('i-items-body').innerHTML='';for(let i=0;i<2;i++)w.addIItem({product:p.name,productCode:p.code,qty:6,priceUnit:100,unit:'ชิ้น'});await w.saveInvoice();assert.equal(w.ERPIntegrity.business().invoices.length,0,JSON.stringify(h.messages));assert.ok(h.messages.some(m=>m.includes('Stock ไม่เพียงพอ'))||w.document.getElementById('app-toast-container')?.textContent.includes('Stock ไม่เพียงพอ'));assert.deepEqual(h.errors,[]);}finally{h.close();}});
test('pricing policy imports into a fresh store and merge keeps a newer policy',async()=>{const h=await boot(),{w}=h;try{const key=w.ComformTenant.storageKey('comform_business_rules_v1');w.localStorage.removeItem(key);w.testApp.restoreLocalMasterBackup({businessRules:{pricingMethod:'target_margin',rate:35,updatedAt:'2026-08-01'}});assert.equal(w.BusinessRulesService.read().rate,35);w.testApp.restoreLocalMasterBackup({businessRules:{rate:10,updatedAt:'2026-07-01'}});assert.equal(w.BusinessRulesService.read().rate,35);assert.equal(w.testApp.collectLocalMasterBackup().businessRules.rate,35);}finally{h.close();}});
test('failed JSON import rolls back an earlier master update',async()=>{const h=await boot(),{w,set}=h;try{w.testApp.restoreLocalMasterBackup({contacts:[{id:'KEEP',name:'รักษาไว้'}]});const before=w.localStorage.getItem(w.ComformTenant.storageKey('comform_contact_master_v1'));set('import-mode','merge');const bad={masterData:{contacts:[{id:'TEMP',name:'ชั่วคราว'}],orderFlow:{salesOrders:[{}]}}};await w.importJSON({target:{files:[{text:async()=>JSON.stringify(bad)}],value:'file'}});assert.equal(w.localStorage.getItem(w.ComformTenant.storageKey('comform_contact_master_v1')),before);assert.ok(w.document.getElementById('import-json-status').textContent.includes('ไม่สำเร็จ'));assert.deepEqual(h.errors,[]);}finally{h.close();}});
test('sales KPI and customer/product/agency charts use the same nonduplicated basis',async()=>{const h=await boot(),{w}=h;try{const p={id:'P1',no:'P1',date:'2026-09-05',customer:'ลูกค้า',sourceSalesOrderId:'SO1',subtotal:1000,saleTotal:1000,items:[{product:'สินค้า',qty:10,priceUnit:100,saleTotal:1000}]},i={id:'I1',no:'I1',date:'2026-09-05',customer:'ลูกค้า',sourceSalesOrderId:'SO1',subtotal:1000,total:1070,useVat:1,items:[{product:'สินค้า',qty:10,priceUnit:100,saleTotal:1000}]};const d=w.loadFor('ubon',2026,8);d.productions=[p];d.invoices=[i];w.saveFor('ubon',2026,8,d);const a=w.testApp;assert.equal(a.branchStats('ubon',2026,8).st,1000);assert.equal(a.buildDashboardProductCompare(2026,8,['ubon']).total,1000);assert.equal(a.customerRows(2026,8,['ubon'],'all','value')[0].value,1000);assert.equal(a.dashboardAgencyRows(2026,8,['ubon'])[0].value,1000);assert.equal(a.buildMonthlyCustomerLeaderRows(2026,['ubon'])[0].sales,1000);assert.deepEqual(h.errors,[]);}finally{h.close();}});
