const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=n=>fs.readFileSync(path.join(root,n),'utf8');
function context(){
 const memory=new Map(),fields=new Map();const c={console,Date,Intl,Math,Number,String,Map,Set,JSON,queueMicrotask:()=>{},setTimeout:()=>0,clearTimeout(){},CustomEvent:class{},addEventListener(){},dispatchEvent(){},notify(){},confirm:()=>true,
 localStorage:{getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k),key:i=>[...memory.keys()][i]??null,get length(){return memory.size}},
 document:{readyState:'loading',addEventListener(){},getElementById:id=>fields.get(id)||null,querySelectorAll:()=>[],querySelector:()=>null,body:{classList:{add(){},remove(){}}}},
 ComformTenant:{storageKey:k=>'test::'+k,unwrapStorageKey:k=>k.startsWith('test::')?k.slice(6):'',getActiveTenantId:()=> 'test'},memory,fields};c.window=c;vm.createContext(c);vm.runInContext(source('erp-integrity.js'),c);vm.runInContext(source('erp-backup.js'),c);
 c.put=(k,v)=>c.localStorage.setItem(c.ComformTenant.storageKey(k),JSON.stringify(v));c.pack=(d,br='ubon')=>c.put('biz2_'+br+'_2026_09',d);c.flow=d=>c.put('example_erp_order_flow_v3',{salesOrders:[],payments:[],billingNotes:[],...d});return c;
}
const invoice=(over={})=>({id:'INV1',no:'INV690901',branch:'ubon',customer:'ลูกค้า ก',date:'2026-09-05',subtotal:1000,total:1070,useVat:1,items:[{product:'สินค้า',productCode:'P1',qty:10,priceUnit:100}],...over});
const order=()=>({id:'SO1',no:'SO690901',branch:'ubon',customer:'ลูกค้า ก',items:[{id:'L1',product:'สินค้า',productCode:'P1',qty:10,stockQty:10,readyQty:10,priceUnit:100}]});
function flowModule(c){let s=source('erp-order-flow-v3.js').replace('  window.ERPOrderFlow = {','  window.flowInternal={derivedOrderStage,saveBilling,saveBillingPayment,saveFulfillment};\n  window.ERPOrderFlow = {');vm.runInContext(s,c);}
function appFunctions(c,names){let s=source('app.js');for(const name of names){const m=new RegExp('^(?:async )?function '+name+'\\(','m').exec(s);assert.ok(m,name);let start=m.index,nl=s.indexOf('\n',start),end;if(s.slice(start,nl).trimEnd().endsWith('}'))end=nl;else end=nl+/^\}/m.exec(s.slice(nl)).index+1;vm.runInContext(s.slice(start,end),c);}}

test('partial receipt keeps invoice outstanding; printed copy is not duplicate cash',()=>{const c=context(),i=invoice();c.pack({invoices:[i],issuedInvoices:[{...i,id:'PRINT1',sourceInvoiceId:i.id}],receipts:[{id:'R1',invNo:i.no,customer:i.customer,total:300}],issuedReceipts:[{id:'PRINT-R',sourceReceiptId:'R1',invNo:i.no,total:300}]});const s=c.ERPIntegrity.paymentSummary(i);assert.equal(s.paid,300);assert.equal(s.outstanding,770);c.ERPIntegrity.reconcilePayments();assert.equal(c.ERPIntegrity.business().invoices[0].paid,false);});
test('full payment settles invoice; reversal reopens balance',()=>{const c=context(),i=invoice();let p={id:'PAY1',branch:'ubon',allocations:[{invoiceId:i.id,amount:1070}]};c.pack({invoices:[i],receipts:[{id:'R1',paymentId:'PAY1',invNo:i.no,total:1070}]});c.flow({payments:[p]});assert.equal(c.ERPIntegrity.paymentSummary(i).paid,1070);p.voided=true;c.flow({payments:[p]});c.ERPIntegrity.reconcilePayments();assert.equal(c.ERPIntegrity.paymentSummary(i).outstanding,1070);});
test('branch references do not mix identical invoice numbers',()=>{const c=context(),i=invoice();c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:300}]});c.pack({invoices:[{...i,branch:'khonkaen'}]},'khonkaen');assert.equal(c.ERPIntegrity.resolveInvoice({no:i.no}),null);assert.equal(c.ERPIntegrity.paymentSummary({...i,branch:'khonkaen'}).paid,0);});
test('receipt overpayment and customer mismatch blocked; edit excludes its old receipt',()=>{const c=context(),i=invoice();c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:300}]});const r={id:'R1',branch:'ubon',customer:i.customer,invNo:i.no,total:1000};assert.throws(()=>c.ERPIntegrity.validateReceipt(r),/เกิน/);assert.doesNotThrow(()=>c.ERPIntegrity.validateReceipt(r,'R1'));assert.throws(()=>c.ERPIntegrity.validateReceipt({...r,total:1,customer:'ผิด'}),/ลูกค้า/);});
test('SO remains partial after payment for first 3 of 10 units',()=>{const c=context(),o=order(),i=invoice({sourceSalesOrderId:o.id,paid:true,items:[{productCode:'P1',salesOrderLineId:'L1',qty:3}]});c.flow({salesOrders:[o]});c.pack({invoices:[i]});flowModule(c);assert.equal(c.ERPIntegrity.orderProgress(o).items[0].remainingQty,7);assert.equal(c.flowInternal.derivedOrderStage(o),'partial');});
test('SO completes only when all units delivered and paid',()=>{const c=context(),o=order(),i=invoice({sourceSalesOrderId:o.id,items:[{salesOrderLineId:'L1',qty:10}]});c.flow({salesOrders:[o]});c.pack({invoices:[i]});flowModule(c);assert.equal(c.flowInternal.derivedOrderStage(o),'delivered');c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:1070}]});assert.equal(c.flowInternal.derivedOrderStage(o),'completed');});
test('duplicate line requests aggregate and cannot exceed SO remaining',()=>{const c=context(),o=order();c.flow({salesOrders:[o]});assert.throws(()=>c.ERPIntegrity.validateDelivery(invoice({sourceSalesOrderId:o.id,items:[{salesOrderLineId:'L1',qty:6},{salesOrderLineId:'L1',qty:6}]})),/จำนวน/);});
test('delivery edit excludes original quantity but still respects ready quantity',()=>{const c=context(),o=order();o.items[0].readyQty=3;c.flow({salesOrders:[o]});const i=invoice({sourceSalesOrderId:o.id,items:[{salesOrderLineId:'L1',qty:3}]});c.pack({invoices:[i]});assert.throws(()=>c.ERPIntegrity.validateDelivery(i),/จำนวน/);assert.doesNotThrow(()=>c.ERPIntegrity.validateDelivery(i,i.id));});
test('stock guard aggregates duplicate SKU rows and deducts other SO reservations',()=>{const c=context(),p={code:'P1',name:'สินค้า',flowType:'inventory',fulfillmentType:'stock'},o=order();c.productMasterRows=()=>[p];c.productEstimatedStock=()=>10;vm.runInContext(source('erp-production-core.js'),c);assert.equal(c.ERPProductionCore.validateInvoiceStock('ubon',[{productCode:'P1',qty:6},{productCode:'P1',qty:6}]).ok,false);o.items[0].stockQty=8;c.flow({salesOrders:[o]});assert.equal(c.ERPIntegrity.availableStock(p,'ubon'),2);assert.equal(c.ERPIntegrity.availableStock(p,'ubon',o.id),10);assert.equal(c.ERPProductionCore.validateInvoiceStock('ubon',[{productCode:'P1',qty:3}]).ok,false);});
test('product code takes precedence over display name; PO product fields supported',()=>{const c=context();assert.equal(c.ERPIntegrity.productKey({productCode:'P1',product:'ชื่อ'}),'p1');assert.notEqual(c.ERPIntegrity.productKey({productCode:'P1'}),c.ERPIntegrity.productKey({productCode:'P2'}));});
test('merge preserves old rows and newer updates; replace removes absent rows',()=>{const c=context(),old=[{id:'A',updatedAt:'2026-09-05',name:'ใหม่'}],next=[{id:'A',updatedAt:'2026-09-01',name:'เก่า'},{id:'B'}];const merged=c.ERPIntegrity.mergeRows(old,next);assert.equal(merged.length,2);assert.equal(merged[0].name,'ใหม่');assert.equal(c.ERPIntegrity.mergeRows(old,[{id:'B'}],true).length,1);});
test('flow import merges instead of overwriting existing sales orders',()=>{const c=context();c.flow({salesOrders:[{id:'OLD'}]});flowModule(c);c.ERPOrderFlow.importData({salesOrders:[{id:'NEW'}]});assert.equal(c.ERPOrderFlow.getStore().salesOrders.length,2);});
test('backup rejects invalid arrays, unsafe keys and nonnumeric amounts',()=>{const c=context();for(const value of [{quotes:3},{invoices:{}},JSON.parse('{"__proto__":{"x":1}}'),{receipts:[{id:'R1',total:'bad'}]}])assert.throws(()=>c.ERPBackup.validate(value));assert.doesNotThrow(()=>c.ERPBackup.validate({invoices:[invoice()]}));});
test('failed local multi-key write rolls back earlier writes',()=>{const c=context();c.localStorage.setItem('a','old');let once=true;const set=c.localStorage.setItem;c.localStorage.setItem=(k,v)=>{if(k==='b'&&once){once=false;throw Error('quota');}set(k,v);};assert.throws(()=>c.ERPIntegrity.transaction([['a','new'],['b','second']]),/quota/);assert.equal(c.localStorage.getItem('a'),'old');assert.equal(c.localStorage.getItem('b'),null);});
test('backup snapshot restores masters and flow in current tenant only',()=>{const c=context();c.put('master',{id:'A'});c.flow({salesOrders:[{id:'SO1'}]});c.localStorage.setItem('other::master','untouched');const snap=c.ERPBackup.capture();c.put('master',{id:'B'});c.put('extra',[]);c.ERPBackup.restore(snap);assert.equal(c.localStorage.getItem('test::master'),'{"id":"A"}');assert.equal(c.localStorage.getItem('test::extra'),null);assert.equal(c.localStorage.getItem('other::master'),'untouched');});
test('generated payment receipts retain correct tax split and never double cash',()=>{const c=context(),i=invoice();c.pack({invoices:[i]});const p={id:'PAY1',no:'PAY690901',date:'2026-09-05',method:'cash',allocations:[{invoiceId:i.id,branch:'ubon',amount:535}]},store={payments:[p],salesOrders:[]};const rows=c.ERPIntegrity.createPaymentReceipts(p,store);assert.equal(rows[0].subtotal,500);assert.equal(rows[0].vatAmt,35);assert.equal(c.ERPIntegrity.paymentSummary(i).paid,535);assert.equal(c.ERPIntegrity.business().receipts.length,1);});
test('VAT modes add, extract and none are consistent',()=>{const c=context();appFunctions(c,['roundMoneyValue','calculateVatSummary']);for(const [raw,mode,net,vat,total] of [[1000,1,1000,70,1070],[1070,0,1000,70,1070],[1000,2,1000,0,1000]]){const r=c.calculateVatSummary(raw,mode);assert.equal(r.subtotal,net);assert.equal(r.vatAmt,vat);assert.equal(r.total,total);}});
test('target margin 95% and markup over 95% calculate correctly',()=>{const c=context();vm.runInContext(source('business-rules.js'),c);const service=c.BusinessRulesService,policy=service.read();const calc=(pricingMethod,rate)=>service.calculate({baseCost:100,qty:1,discountPercent:0,vatEnabled:false},{policy,pricingMethod,rate,discountPercent:0}).listUnit;assert.equal(Math.round(calc('target_margin',95)),2000);assert.equal(calc('markup_on_cost',150),250);});
test('direct inventory invoices count as sales; SO production is not counted twice',()=>{const c=context(),i=invoice({sourceSalesOrderId:'SO1'}),p={id:'P1',sourceSalesOrderId:'SO1',subtotal:1000};c.pack({invoices:[i],productions:[p]});appFunctions(c,['analyticsPrimarySalesRows']);const rows=c.analyticsPrimarySalesRows({invoices:[i],productions:[p]});assert.equal(rows.length,1);assert.equal(rows[0]._type,'invoices');});
test('invalid quantities and nonfinite prices are rejected',()=>{const c=context();for(const item of [{product:'X',qty:0},{product:'X',qty:1,priceUnit:'no'},{product:'X',qty:-1}])assert.throws(()=>c.ERPIntegrity.validateItems([item]));});
test('portable backup permits Thai attachment filenames',()=>{const c=context();assert.doesNotThrow(()=>c.ERPBackup.validate({meta:{backupSchemaVersion:4},localFiles:[{id:'local-tenant-ใบเสร็จ ลูกค้า.pdf',name:'ใบเสร็จ ลูกค้า.pdf'}]}));});
test('delivery and payment references reject customer, SKU and invoice-number mismatches',()=>{const c=context(),o=order(),i=invoice();c.flow({salesOrders:[o]});c.pack({invoices:[i]});assert.throws(()=>c.ERPIntegrity.validateDelivery(invoice({sourceSalesOrderId:o.id,customer:'ผิด',items:[{salesOrderLineId:'L1',qty:1}]})),/ลูกค้า/);assert.throws(()=>c.ERPIntegrity.validateDelivery(invoice({sourceSalesOrderId:o.id,items:[{salesOrderLineId:'L1',productCode:'WRONG',qty:1}]})),/สินค้า/);assert.throws(()=>c.ERPIntegrity.validateReceipt({branch:'ubon',customer:i.customer,invoiceId:i.id,invNo:'WRONG',total:10}),/เลขบิล/);});
test('billing excludes receipts already applied before it was created',()=>{const c=context(),i=invoice(),b={id:'B1',status:'draft',lines:[{invoiceId:i.id,branch:'ubon',billedAmount:770,receiptPaidAtCreation:300}]},store={payments:[],billingNotes:[b]};c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:300}]});c.ERPIntegrity.reconcileBillings(store);assert.equal(b.outstandingAmount,770);c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:400}]});c.ERPIntegrity.reconcileBillings(store);assert.equal(b.outstandingAmount,670);assert.equal(b.status,'partially_paid');});
test('billing direct receipts allocate FIFO and reverse without double payment',()=>{const c=context(),i=invoice();const a={id:'B1',status:'draft',billingDate:'2026-09-01',lines:[{invoiceId:i.id,billedAmount:300,receiptPaidAtCreation:0}]},b={id:'B2',status:'draft',billingDate:'2026-09-02',lines:[{invoiceId:i.id,billedAmount:770,receiptPaidAtCreation:300}]},store={billingNotes:[a,b],payments:[]};c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:350}]});c.ERPIntegrity.reconcileBillings(store);assert.equal(a.paidAmount,300);assert.equal(b.paidAmount,50);c.pack({invoices:[i],receipts:[]});c.ERPIntegrity.reconcileBillings(store);assert.equal(a.status,'draft');assert.equal(b.status,'draft');});
test('production costs are allocated over partial deliveries with final cent retained',()=>{const c=context(),o=order();o.items[0].qty=3;o.items[0].productionQty=3;c.flow({salesOrders:[o]});const production={id:'PROD',sourceSalesOrderId:o.id,costTotal:100,items:[{salesOrderLineId:'L1',qty:3,costTotal:100}]};const invoices=[];for(let n=0;n<3;n++){c.pack({productions:[production],invoices});const cost=c.ERPIntegrity.salesOrderCost(o.id,'L1',1);assert.ok(Math.abs(cost.total-100/3)<0.01);if(n===2)assert.equal(cost.total,Math.round((100-invoices.reduce((s,i)=>s+i.items[0].costTotal,0))*100)/100);assert.equal(cost.basis,'production_actual');invoices.push(invoice({id:'I'+n,no:'N'+n,sourceSalesOrderId:o.id,items:[{salesOrderLineId:'L1',qty:1,costTotal:cost.total}]}));}assert.equal(invoices.reduce((s,i)=>s+i.items[0].costTotal,0),100);});
test('legacy billing migrates its already-paid creation balance once',()=>{const c=context(),i=invoice(),b={id:'B1',status:'draft',lines:[{invoiceId:i.id,originalAmount:1070,outstandingAmount:770,billedAmount:770}]},store={billingNotes:[b],payments:[]};c.pack({invoices:[i],receipts:[{id:'R1',invNo:i.no,total:300}]});c.ERPIntegrity.reconcileBillings(store);assert.equal(b.outstandingAmount,770);assert.equal(b.lines[0].receiptPaidAtCreation,300);c.ERPIntegrity.reconcileBillings(store);assert.equal(b.outstandingAmount,770);});
test('a production record without cost evidence cannot label zero cost as actual',()=>{const c=context(),o=order();o.items[0].productionQty=10;c.flow({salesOrders:[o]});c.pack({productions:[{id:'P',sourceSalesOrderId:o.id,items:[{salesOrderLineId:'L1',qty:10}]}]});assert.equal(c.ERPIntegrity.salesOrderCost(o.id,'L1',10).basis,'missing');});
