const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ROOT=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(ROOT,f),'utf8');
test('4.3 release metadata is aligned',()=>{const p=JSON.parse(read('package.json'));assert.equal(p.erpRelease,'4.3.0');assert.equal(p.version,'2.3.0');assert.match(read('index.html'),/4\.3\.0-source/);});
test('issued documents are locked against destructive delete',()=>{const s=read('app.js');assert.match(s,/type==='issuedInvoices'\|\|type==='issuedReceipts'/);assert.doesNotMatch(s,/issuedInvoices'[^\n]{0,220}>ลบ<\/button>/);assert.doesNotMatch(s,/issuedReceipts'[^\n]{0,220}>ลบ<\/button>/);});
test('issued document detail uses open modal lifecycle',()=>{const s=read('app.js');const i=s.indexOf('function showIssuedDocumentDetail');const part=s.slice(i,i+1800);assert.match(part,/classList\.add\('open'\)/);assert.doesNotMatch(part,/classList\.add\('show'\)/);});
test('attachment URL guard blocks javascript and html data URLs',async()=>{const src=read('erp-detail-security.js').replace(/export /g,'');assert.match(src,/https:/);assert.match(src,/blob:/);assert.doesNotMatch(src,/javascript:/);});
test('data-driven order and production ids are not interpolated into inline onclick',()=>{const a=read('erp-order-flow.js'),b=read('erp-production-core.js');assert.doesNotMatch(a,/onclick=\"ERPOrderFlow\.[^\"]*\$\{[^}]*\.id/);assert.doesNotMatch(b,/onclick=\"pc(?:UsePoForReceipt|CancelPo|ReverseGr|RestoreTrash)\('\$\{/);assert.match(a,/data-order-action=/);assert.match(b,/data-prodcore-action=/);});
test('master actions archive rather than hard-delete',()=>{const s=read('app.js');assert.match(s,/function archiveContactMaster/);assert.match(s,/function archiveProductMasterLocal/);assert.match(s,/active:false/);});
test('same-browser document save lease wraps quote invoice and receipt',()=>{const s=read('app.js');for(const n of ['quote','invoice','receipt'])assert.match(s,new RegExp(`withDemoWriteLease\\('${n}'`));});
test('trial banner states multi-user production limitation',()=>assert.match(read('index.html'),/ยังไม่ใช่ระบบ Production หลายผู้ใช้/));
